config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'canceled', on: :member
    post 'delivered', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index] 
    end
  end
end

app/models/product_model.rb
class ProductModel < ApplicationRecord
  belongs_to :supplier
  has_many :order_items
  has_many :orders, through: :order_items

  validates :name, :weight, :width, :height, :depth, :sku, presence: true
  validates :sku, length: { is: 20 }
  validates :sku, uniqueness: true
  validates :weight, :width, :height, :depth, numericality: { greater_than: 0 }

  def dimensions
    "#{width} cm x #{depth} cm x #{height} cm"    
  end
end

app/controllers/product_models_controller.rb
class ProductModelsController < ApplicationController

  def index
    @product_models = ProductModel.all.order(:name)
  end

  def show
    @product_model = ProductModel.find(params[:id])
  end

  def new
    @product_model = ProductModel.new
    @suppliers = Supplier.all.order(:brand_name)
  end

  def create
    product_model_params = params.require(:product_model).permit(:name, :weight, :width, :height, 
                                          :depth, :sku, :supplier_id)
    @product_model = ProductModel.new(product_model_params)
    if @product_model.save
      redirect_to @product_model, notice: t(:product_model_creation_success)
    else
      @suppliers = Supplier.all.order(:brand_name)
      flash.now[:alert] = t(:product_model_creation_error)
      render 'new'
    end
  end
end

app/views/product_models/_form.html.erb
<%= form_with(model: @product_model) do |f| %>
  <div class="mb-3">
    <%= f.label :name, class: "form-label fw-semibold" %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
    <div class="mb-3">
    <%= f.label :sku, class: "form-label fw-semibold" %>
    <%= f.text_field :sku, class: "form-control", maxlength: 20 %>
  </div>
  <div class="mb-3">
      <%= f.label :weight, class: "form-label fw-semibold" %>
      <%= f.number_field :weight, class: "form-control", placeholder: t(:weight_g) %>
  </div>
  <div class="row mb-3">
    <div class="col">
      <%= f.label :width, class: "form-label fw-semibold" %>
      <%= f.number_field :width, class: "form-control", placeholder: t(:width_cm) %>
    </div>
    <div class="col">
      <%= f.label :depth, class: "form-label fw-semibold" %>
      <%= f.number_field :depth, class: "form-control", placeholder: t(:depth_cm) %>
    </div>
    <div class="col">
      <%= f.label :height, class: "form-label fw-semibold" %>
      <%= f.number_field :height, class: "form-control", placeholder: t(:height_cm) %>
    </div>
  </div>
  <div class="d-grid col-4 mb-3">
      <%= f.label :supplier_id, class: "form-label fw-semibold" %>
      <%= f.collection_select :supplier_id, @suppliers, :id, :brand_name, prompt: true %>
  </div>
  <div class="d-grid gap-2 col-4 mb-3">
    <%= f.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/product_models/index.html.erb
<h1 class="my-3"><%= ProductModel.model_name.human count: 2 %></h1>

<div class="my-3">
  <%= link_to "#{ t(:register) } #{ ProductModel.model_name.human }", new_product_model_path, class: "btn btn-outline-dark " %>
</div>

<% if @product_models.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= ProductModel.human_attribute_name(:name) %></th>
        <th scope="col"><%= ProductModel.human_attribute_name(:sku) %></th>
        <th scope="col"><%= ProductModel.human_attribute_name(:supplier) %></th>
      </tr>
    </thead>
    <tbody>
      <% @product_models.each do |pm| %>
        <tr>
          <td><%= link_to pm.name, pm, class: "link-dark" %></td>
          <td><%= pm.sku %></td>
          <td><%= link_to pm.supplier.brand_name, supplier_path(pm.supplier), class: "link-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-secondary text-center" role="alert">
    <%= t(:no_product_model_registered) %>
  </div>
<% end %>




app/views/product_models/new.html.erb
<h1 class="my-3"><%= t(:new) %> <%= ProductModel.model_name.human %></h1>

<% if(@product_model.errors.any?) %>
  <div class="alert alert-danger" role="alert">
    <p><%= t(:check_errors) %></p>
    <ul>
      <% @product_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/product_models/show.html.erb
<h1 class="my-3"><%= ProductModel.model_name.human %>: <%= @product_model.name %></h1>
<h5 class="my-3"><%= ProductModel.human_attribute_name(:sku) %>: <%= @product_model.sku %></h5>


<dl>
  <dt class="fw-semibold"><%= t(:dimensions) %>:</dt>
  <dd><%= @product_model.dimensions %></dd>
  <dt class="fw-semibold"><%= ProductModel.human_attribute_name(:weight) %>:</dt>
  <dd><%= number_to_human(@product_model.weight, units: {unit: 'g', thousand: 'kg'}) %></dd>
  <dt class="fw-semibold"><%= ProductModel.human_attribute_name(:supplier) %>:</dt>
  <dd><%= link_to @product_model.supplier.brand_name, supplier_path(@product_model.supplier), class: "link-dark" %></dd>  
</dl>


<div class="d-grid gap-2 col-4 mb-3">
  <%= link_to t(:back), product_models_path, class:"btn btn-outline-dark" %>
</div>