config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'canceled', on: :member
    post 'delivered', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index] 
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 10, canceled: 20,  delivered: 30}

  belongs_to :warehouse
  belongs_to :supplier
  belongs_to :user
  has_many :order_items
  has_many :product_models, through: :order_items

  validates :code, :estimated_delivery_date, presence: true
  validates :estimated_delivery_date, comparison: { greater_than: Date.today, message: 'deve ser futura' }

  before_validation :generate_code, on: :create

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(10).upcase
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order_and_check_user, only: [:show, :edit, :update, :delivered, :canceled]
  before_action :set_warehouses_and_suppliers, only: [:new, :edit]

  def index
    @orders = current_user.orders
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    @order.user = current_user

    if @order.save
      redirect_to @order, notice: t(:order_creation_success)
    else
      @warehouses = Warehouse.all.order(:name)
      @suppliers = Supplier.all.order(:corporate_name)
      flash.now[:alert] = t(:order_creation_error)
      render 'new'
    end
  end

  def show; end

  def edit; end

  def update
    if @order.update(order_params)
      redirect_to @order, notice: t(:order_update_success)
    else
      flash.now[:alert] = t(:order_update_error)
      @warehouses = Warehouse.all.order(:name)
      @suppliers = Supplier.all.order(:corporate_name)
      render 'edit'
    end
  end

  def canceled
    @order.canceled!
    redirect_to @order
  end

  def delivered
    @order.delivered!
    @order.order_items.each { |oi| oi.create_stock_product }
    redirect_to @order
  end

  def search
    @code = params[:query]
    @orders = Order.where("code LIKE ?", "%#{@code}%")
  end

  private

  def set_order_and_check_user
    @order = Order.find(params[:id])
    
    if @order.user != current_user
      return redirect_to root_url, alert: t(:order_access_error)
    end
  end

  def set_warehouses_and_suppliers
    @warehouses = Warehouse.all.order(:name)
    @suppliers = Supplier.all.order(:corporate_name)
  end

  def order_params
    params.require(:order).permit(:warehouse_id, :supplier_id, :estimated_delivery_date)
  end
end

app/views/orders/_form.html.erb
<%= form_with(model: @order) do |f| %>
  <div class="d-grid gap-2 col-4 mb-3">
    <%= f.label :warehouse_id, class: "form-label fw-semibold" %>
    <%= f.collection_select :warehouse_id, @warehouses, :id, :warehouse_full_description, prompt: true %>
  </div>
  <div class="d-grid gap-2 col-4 mb-3">
    <%= f.label :supplier_id, class: "form-label fw-semibold" %>
    <%= f.collection_select :supplier_id, @suppliers, :id, :supplier_full_description, prompt: true %>
  </div>
  <div class="d-grid gap-2 col-4 mb-3">
    <%= f.label :estimated_delivery_date, class: "form-label fw-semibold" %>
    <%= f.date_field :estimated_delivery_date, class: "form-control" %>
  </div>
  <div class="d-grid gap-2 col-4 mb-3">
    <%= f.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1 class="my-3"><%= t(:edit) %> <%= Order.model_name.human %></h1>

<%= render 'form' %>

app/views/orders/index.html.erb
<h1 class="my-3"><%= t(:my_masc, count: 2) %> <%= Order.model_name.human count: 2 %></h1>

<div class="my-3">
  <%= link_to "#{ t(:register) } #{ Order.model_name.human }", new_order_path, class: "btn btn-outline-dark " %>
</div>

<% if @orders.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= Order.model_name.human %></th>
        <th scope="col"><%= Order.human_attribute_name(:supplier) %></th>
        <th scope="col"><%= Order.human_attribute_name(:warehouse) %></th>
        <th scope="col"><%= Order.human_attribute_name(:estimated_delivery_date) %></th>
        <th scope="col"><%= Order.human_attribute_name(:status) %></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |order| %>
        <tr>
          <td><%= link_to order.code, order, class: "link-dark" %></td>
          <td><%= link_to order.supplier.supplier_full_description, order.supplier, class: "link-dark" %></td>
          <td><%= link_to order.warehouse.warehouse_full_description, order.warehouse, class: "link-dark" %></td>
          <td><%= I18n.l(order.estimated_delivery_date) %></td>
          <td><%= Order.human_attribute_name("status.#{order.status}") %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-secondary text-center" role="alert">
    <%= t(:no_order_registered) %>
  </div>
<% end %>

app/views/orders/new.html.erb
<h1 class="my-3"><%= t(:new) %> <%= Order.model_name.human %></h1>

<% if(@order.errors.any?) %>
  <div class="alert alert-danger" role="alert">
    <p><%= t(:check_errors) %></p>
    <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render 'form' %>

app/views/orders/search.html.erb
<h2 class="my-3"><%= t(:search_results) %> <%= @code %></h2>

<% if @orders.any? %>
  <div class="alert alert-success" role="alert">
    <%= @orders.count %> <%= Order.model_name.human(count: @orders.count).downcase %> <%= t(:found, count: @orders.count) %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= Order.human_attribute_name(:code) %></th>
        <th scope="col"><%= Order.human_attribute_name(:estimated_delivery_date) %></th>
        <th scope="col"><%= Order.human_attribute_name(:supplier) %></th>
        <th scope="col"><%= Order.human_attribute_name(:warehouse) %></th>
      </tr>
    </thead>
    <tbody>
      <% @orders.each do |o| %>
        <tr>
          <td><%= link_to o.code, o, class: "link-dark" %></td>
          <td><%= I18n.l(o.estimated_delivery_date) %></td>
          <td><%= link_to o.supplier.supplier_full_description, o.supplier, class: "link-dark" %></td>
          <td><%= link_to o.warehouse.warehouse_full_description, o.warehouse, class: "link-dark" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-danger" role="alert">
    <%= t(:order_not_found) %>
  </div>
<% end %>


app/views/orders/show.html.erb
<h1 class="my-3"><%= Order.model_name.human %> <%= @order.code %></h1>
<h3 class="text-muted"><%= Order.human_attribute_name(:status) %>: <%= Order.human_attribute_name("status.#{@order.status}") %></h3>

<% if @order.pending? %>
  <div class="d-grid gap-2 col-4 my-3">
    <%= button_to t(:mark_as_delivered), delivered_order_path(@order.id), class: "btn btn-dark" %>
  </div>

  <div class="d-grid gap-2 col-4 my-3">
    <%= button_to t(:mark_as_canceled), canceled_order_path(@order.id), class: "btn btn-outline-dark" %>
  </div>
<% end %>

<dl>
  <dt class="fw-semibold"><%= Order.human_attribute_name(:estimated_delivery_date) %>:</dt>
  <dd><%= I18n.l(@order.estimated_delivery_date) %></dd>
  <dt class="fw-semibold"><%= Order.human_attribute_name(:warehouse) %>:</dt>
  <dd><%= link_to @order.warehouse.warehouse_full_description, @order.warehouse, class: "link-dark" %></dd>
  <dt class="fw-semibold"><%= Order.human_attribute_name(:supplier) %>:</dt>
  <dd><%= link_to @order.supplier.supplier_full_description, @order.supplier, class: "link-dark" %></dd>
  <dt class="fw-semibold"><%= Order.human_attribute_name(:user) %>:</dt>
  <dd><%= @order.user.user_full_description %></dd>
</dl>

<h2 class="my-3"><%= OrderItem.model_name.human count: 2 %></h2>

<%= link_to 'Adicionar Item', new_order_order_item_path(@order.id), class:"btn btn-outline-dark" %>

<ul class="my-3">
  <% @order.order_items.each do |item| %>
    <li><%= item.quantity %> x <%= item.product_model.name %></li>
  <% end %>
</ul>

<div class="row">
  <% if @order.pending? %>
    <div class="d-grid gap-2 col-4 my-3">
      <%= link_to "#{ t(:edit) } #{ Order.model_name.human }", edit_order_path, class: "btn btn-dark" %>
    </div>
  <% end %>
  <div class="d-grid gap-2 col-4 my-3">
    <%= link_to t(:back), orders_path, class:"btn btn-outline-dark" %>
  </div>
</div>