config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'canceled', on: :member
    post 'delivered', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index] 
    end
  end
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :product_models
  
  validates :brand_name, :corporate_name, :registration_number, :email, presence: true
  validates :registration_number, uniqueness: true
  validates :registration_number, length: { is: 14 }
  validates :postal_code, format: { with: /\A\d{5}-{1}\d{3}\z/ }

  def supplier_full_description
    "#{brand_name} - #{corporate_name}"
  end

  def formatted_registration_number
    "#{registration_number[0, 2]}.#{registration_number[2, 3]}.#{registration_number[5, 3]}/#{
     registration_number[8, 4]}-#{registration_number[12, 2]}"
  end

  def formatted_address
    "#{full_address} - #{city} - #{state}"
  end
end

app/controllers/suppliers_controller.rb
class SuppliersController < ApplicationController
  before_action :set_supplier, only: [:show, :edit, :update]
  
  def index
    @suppliers = Supplier.all.order(:brand_name)
  end

  def new
    @supplier = Supplier.new
  end

  def create
    @supplier = Supplier.new(supplier_params)

    if @supplier.save
      redirect_to supplier_url(@supplier.id), notice: t(:supplier_creation_success)
    else
      flash.now[:alert] = t(:supplier_creation_error)
      render 'new'
    end
  end

  def show
    @product_models = @supplier.product_models.order(:name)
  end

  def edit; end

  def update
    if @supplier.update(supplier_params)
      redirect_to supplier_url(@supplier.id), notice: t(:supplier_update_success)
    else
      flash.now[:alert] = t(:supplier_update_error)
      render 'edit'
    end
  end

  private

  def set_supplier
    @supplier = Supplier.find(params[:id])
  end
  
  def supplier_params
    params.require(:supplier).permit(:corporate_name, :brand_name, :registration_number, :full_address, 
                                      :city, :state, :email, :postal_code, :phone_number)
  end
end

app/views/suppliers/_form.html.erb
<%= form_with(model: @supplier) do |f| %>
  <div class="mb-3">
    <%= f.label :brand_name, class: "form-label fw-semibold" %>
    <%= f.text_field :brand_name, class: "form-control" %>
  </div>
    <div class="mb-3">
    <%= f.label :corporate_name, class: "form-label fw-semibold" %>
    <%= f.text_field :corporate_name, class: "form-control" %>
  </div>
  <div class="mb-3">
      <%= f.label :registration_number, class: "form-label fw-semibold" %>
      <%= f.text_field :registration_number, class: "form-control", placeholder: t(:only_numbers), maxlength: 14 %>
  </div>
  <div class="mb-3">
      <%= f.label :full_address, class: "form-label fw-semibold" %>
      <%= f.text_field :full_address, class: "form-control" %>
  </div>
  <div class="row mb-3">
    <div class="col">
      <%= f.label :city, class: "form-label fw-semibold" %>
      <%= f.text_field :city, class: "form-control" %>
    </div>
    <div class="col">
      <%= f.label :state, class: "form-label fw-semibold" %>
      <%= f.text_field :state, class: "form-control" %>
    </div>
    <div class="col">
      <%= f.label :postal_code, class: "form-label fw-semibold" %>
      <%= f.text_field :postal_code, class: "form-control", placeholder: '00000-000', maxlength: 9 %>
    </div>
  </div>
  <div class="mb-3">
    <%= f.label :email, class: "form-label fw-semibold" %>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= f.label :phone_number, class: "form-label fw-semibold" %>
    <%= f.text_field :phone_number, class: "form-control", placeholder: t(:only_numbers), maxlength: 11 %>
  </div>
  <div class="d-grid gap-2 col-4 mb-3">
    <%= f.submit class: "btn btn-dark" %>
  </div>
<% end %>

app/views/suppliers/edit.html.erb
<h1 class="my-3"><%= t(:edit) %> <%= Supplier.model_name.human %></h1>

<%= render 'form' %>

app/views/suppliers/index.html.erb
<h1 class="my-3"><%= Supplier.model_name.human(count: 2) %></h1>

<div class="my-3">
  <%= link_to "#{ t(:register) } #{ Supplier.model_name.human }", new_supplier_path, class: "btn btn-outline-dark " %>
</div>

<% if @suppliers.any? %>
  <table class="table">
    <thead>
      <tr>
        <th scope="col"><%= Supplier.human_attribute_name(:brand_name) %></th>
        <th scope="col"><%= Supplier.human_attribute_name(:state) %></th>
      </tr>
    </thead>
    <tbody>
      <% @suppliers.each do |s| %>
        <tr>
          <td><%= link_to s.brand_name, s, class: "link-dark" %></td>
          <td><%= s.city %> - <%= s.state %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-secondary text-center" role="alert">
    <%= t(:no_supplier_registered) %>
  </div>
<% end %>

app/views/suppliers/new.html.erb
<h1 class="my-3"><%= t(:new) %> <%= Supplier.model_name.human %></h1>

<% if(@supplier.errors.any?) %>
  <div class="alert alert-danger" role="alert">
    <p><%= t(:check_errors) %></p>
    <ul>
      <% @supplier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= render 'form' %>

app/views/suppliers/show.html.erb
<h1 class="my-3"><%= @supplier.brand_name %></h1>
<h4 class="my-3"><%= @supplier.corporate_name %></h4>

<div>
  <dl>
    <dt class="fw-semibold"><%= Supplier.human_attribute_name(:registration_number) %>:</dt>
    <dd>
    <%= @supplier.formatted_registration_number %>
    </dd>
    <dt class="fw-semibold"><%= Supplier.human_attribute_name(:full_address) %>:</dt>
    <dd><%= @supplier.formatted_address %></dd>
    <dt class="fw-semibold"><%= Supplier.human_attribute_name(:postal_code) %>:</dt>
    <dd><%= @supplier.formatted_postal_code %></dd>
    <dt class="fw-semibold"><%= Supplier.human_attribute_name(:phone_number) %>:</dt>
    <dd><%= number_to_phone(@supplier.phone_number, pattern: /(\d{1,5})(\d{5})(\d{4})$/, area_code: true) %></dd>
    <dt class="fw-semibold"><%= Supplier.human_attribute_name(:email) %>:</dt>
    <dd><%= @supplier.email %></dd>
  </dl>
</div>

<div class="row">
  <div class="d-grid gap-2 col-4 my-3">
    <%= link_to "#{ t(:edit) } #{ Supplier.model_name.human }", edit_supplier_path, class: "btn btn-dark" %>
  </div>
  <div class="d-grid gap-2 col-4 my-3">
    <%= link_to t(:back), suppliers_path, class:"btn btn-outline-dark" %>
  </div>    
</div>  

<% if @product_models.empty? %>
  <div class="alert alert-secondary text-center" role="alert">
    <%= t(:no_product_model_for_supplier) %>
  </div>
<% else %>
  <h4 class="my-3"><%= t(:registered_product_models) %></h4>
  <% @product_models.each do |pm| %>
    <div class="card my-3">
      <div class="card-body">
        <h5 class="card-title"><%= pm.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted"><%= ProductModel.human_attribute_name(:sku) %>: <%= pm.sku %></h6>
        <dl class="card-text">
          <dt class="fw-semibold"><%= ProductModel.human_attribute_name(:weight) %>:</dt>
          <dd><%= number_to_human(pm.weight, units: {unit: 'g', thousand: 'kg'}) %></dd>
          <dt class="fw-semibold"><%= t(:dimensions) %>:</dt>
          <dd><%= pm.dimensions %></dd>
        </dl>  
      </div>
    </div>
  <% end %>        
<% end %>