config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'home#index'
  resources :warehouses, only: [:show, :new, :create, :edit, :update, :destroy] do
    resources :stock_product_destinations, only: [:create]
  end
  resources :suppliers, only: [:index, :show, :new, :create, :edit, :update]
  resources :product_models, only: [:index, :new, :create, :show]
  
  resources :orders, only: [:new, :create, :show, :index, :edit, :update] do
    resources :order_items, only: [:new, :create]
    get 'search', on: :collection
    post 'canceled', on: :member
    post 'delivered', on: :member
  end

  namespace :api do
    namespace :v1 do
      resources :warehouses, only: [:show, :index] 
    end
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type, msg| %>
  <% if type == 'alert' %>
    <div class='alert alert-danger' >
      <%= msg %>
    </div>
  <% else %>
    <div class='alert alert-success' >
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to t(:warehouses_and_storage), root_path, class: 'navbar-brand' %>
    
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to Supplier.model_name.human(count: 2), suppliers_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to t(:product, count: 2), product_models_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "#{ t(:my_masc, count: 2) } #{ Order.model_name.human(count: 2) }", orders_path, class: 'nav-link' %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name %>
            </a>
            <ul class="dropdown-menu dropdown-menu-lg-end">
              <%= button_to t(:logout), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
           </ul>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li>
            <%= form_with(url: search_orders_path, method: :get, class: 'd-flex') do |f| %>
              <%= f.text_field :query, placeholder: "#{ t(:search) } #{ Order.model_name.human }", class: "form-control me-2" %>
              <%= f.submit t(:search), class: "btn btn-dark" %>
            <% end %>
          </li>
        </ul>
      </div>
    <% else %>
      <ul class="navbar-nav">
        <%= link_to t(:sign_in),  new_user_session_path, class: "btn btn-outline-dark" %>
      </ul>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t(:warehouses_and_storage) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <div class="container">
        <div class="my-3" >
          <%= render 'layouts/flash_messages' %>
        </div>
        <%= yield %>
      </div>
    </main>
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" 
            crossorigin="anonymous">
    </script>
  </body>
</html>